import {
  runSum, runFactorialRecursive, runFactorialIterative,
  runFibonacciRecursive, runFibonacciIterative,
  runBubbleSortIterative, runBubbleSortRecursive,
  runInsertionSortIterative, runInsertionSortRecursive,
  runBinarySearchIterative, runBinarySearchRecursive,
  runBFSIterative, runBFSRecursive,
  runDFSIterative, runDFSRecursive,
} from './engines';

export const CATEGORIES = {
  Math:    { color: '#38bdf8', glow: 'rgba(56,189,248,0.3)',  icon: '∑' },
  Sorting: { color: '#34d399', glow: 'rgba(52,211,153,0.3)',  icon: '⇅' },
  Search:  { color: '#a78bfa', glow: 'rgba(167,139,250,0.3)', icon: '◎' },
  Graph:   { color: '#fb923c', glow: 'rgba(251,146,60,0.3)',  icon: '⬡' },
};

// inputType: 'number' | 'array' | 'search' | 'graph'
export const ALGORITHMS = [
  {
    id: 'sum',
    label: 'Sum',
    sublabel: 'Recursive',
    category: 'Math',
    description: 'Computes the sum 1+2+…+n using recursion. Each call reduces n by 1 until the base case.',
    complexity: { time: 'O(n)', space: 'O(n)' },
    inputType: 'number',
    defaultInput: '10',
    inputLabel: 'Enter n',
    inputHint: 'A positive integer (e.g. 10)',
    run: runSum,
  },
  {
    id: 'factorial_recursive',
    label: 'Factorial',
    sublabel: 'Recursive',
    category: 'Math',
    description: 'Computes n! by calling fact(n-1) recursively. Stack depth equals n.',
    complexity: { time: 'O(n)', space: 'O(n)' },
    inputType: 'number',
    defaultInput: '8',
    inputLabel: 'Enter n',
    inputHint: 'A positive integer (e.g. 8). Keep ≤ 15 to avoid overflow.',
    run: runFactorialRecursive,
  },
  {
    id: 'factorial_iterative',
    label: 'Factorial',
    sublabel: 'Iterative',
    category: 'Math',
    description: 'Computes n! using a single loop. Constant stack space, one call.',
    complexity: { time: 'O(n)', space: 'O(1)' },
    inputType: 'number',
    defaultInput: '8',
    inputLabel: 'Enter n',
    inputHint: 'A positive integer (e.g. 8).',
    run: runFactorialIterative,
  },
  {
    id: 'fibonacci_recursive',
    label: 'Fibonacci',
    sublabel: 'Recursive',
    category: 'Math',
    description: 'Computes the nth Fibonacci number via double recursion. Exponential calls — watch it grow!',
    complexity: { time: 'O(2ⁿ)', space: 'O(n)' },
    inputType: 'number',
    defaultInput: '10',
    inputLabel: 'Enter n',
    inputHint: 'Recommended ≤ 20 (exponential calls!)',
    run: runFibonacciRecursive,
  },
  {
    id: 'fibonacci_iterative',
    label: 'Fibonacci',
    sublabel: 'Iterative',
    category: 'Math',
    description: 'Computes the nth Fibonacci number by iterating forward. Linear time, constant space.',
    complexity: { time: 'O(n)', space: 'O(1)' },
    inputType: 'number',
    defaultInput: '10',
    inputLabel: 'Enter n',
    inputHint: 'Any positive integer.',
    run: runFibonacciIterative,
  },
  {
    id: 'bubble_sort_iterative',
    label: 'Bubble Sort',
    sublabel: 'Iterative',
    category: 'Sorting',
    description: 'Repeatedly swaps adjacent elements that are out of order. Classic nested loop approach.',
    complexity: { time: 'O(n²)', space: 'O(1)' },
    inputType: 'array',
    defaultInput: '5, 8, 3, 1, 9, 2, 7',
    inputLabel: 'Enter array',
    inputHint: 'Comma-separated numbers (e.g. 5, 8, 3, 1)',
    run: runBubbleSortIterative,
  },
  {
    id: 'bubble_sort_recursive',
    label: 'Bubble Sort',
    sublabel: 'Recursive',
    category: 'Sorting',
    description: 'Recursively bubbles the largest unsorted element to the end each pass.',
    complexity: { time: 'O(n²)', space: 'O(n)' },
    inputType: 'array',
    defaultInput: '5, 8, 3, 1, 9, 2, 7',
    inputLabel: 'Enter array',
    inputHint: 'Comma-separated numbers.',
    run: runBubbleSortRecursive,
  },
  {
    id: 'insertion_sort_iterative',
    label: 'Insertion Sort',
    sublabel: 'Iterative',
    category: 'Sorting',
    description: 'Builds the sorted array one element at a time by inserting into the correct position.',
    complexity: { time: 'O(n²)', space: 'O(1)' },
    inputType: 'array',
    defaultInput: '9, 6, 10, 1, 0, 4',
    inputLabel: 'Enter array',
    inputHint: 'Comma-separated numbers.',
    run: runInsertionSortIterative,
  },
  {
    id: 'insertion_sort_recursive',
    label: 'Insertion Sort',
    sublabel: 'Recursive',
    category: 'Sorting',
    description: 'Recursively sorts the first n-1 elements, then inserts the nth into position.',
    complexity: { time: 'O(n²)', space: 'O(n)' },
    inputType: 'array',
    defaultInput: '9, 6, 10, 1, 0, 4',
    inputLabel: 'Enter array',
    inputHint: 'Comma-separated numbers.',
    run: runInsertionSortRecursive,
  },
  {
    id: 'binary_search_iterative',
    label: 'Binary Search',
    sublabel: 'Iterative',
    category: 'Search',
    description: 'Finds a target in a sorted array by halving the search space each step.',
    complexity: { time: 'O(log n)', space: 'O(1)' },
    inputType: 'search',
    defaultInput: { arr: '3, 1, 4, 9, 0, 2', target: '4' },
    inputLabel: 'Array & target',
    inputHint: 'Array: comma-separated numbers. Target: a number to find.',
    run: runBinarySearchIterative,
  },
  {
    id: 'binary_search_recursive',
    label: 'Binary Search',
    sublabel: 'Recursive',
    category: 'Search',
    description: 'Same as iterative but uses recursive calls instead of a loop.',
    complexity: { time: 'O(log n)', space: 'O(log n)' },
    inputType: 'search',
    defaultInput: { arr: '3, 1, 4, 9, 0, 2', target: '4' },
    inputLabel: 'Array & target',
    inputHint: 'Array: comma-separated numbers. Target: a number to find.',
    run: runBinarySearchRecursive,
  },
  {
    id: 'bfs_iterative',
    label: 'BFS',
    sublabel: 'Iterative',
    category: 'Graph',
    description: 'Explores a graph level by level using a queue. Visits all neighbors before going deeper.',
    complexity: { time: 'O(V+E)', space: 'O(V)' },
    inputType: 'graph',
    defaultInput: {
      nodes: 'A, B, C, D, E',
      edges: 'A-B, A-C, B-D, C-E',
      start: 'A',
    },
    inputLabel: 'Graph & start node',
    inputHint: 'Nodes: comma-separated. Edges: node-node pairs. Start: starting node.',
    run: runBFSIterative,
  },
  {
    id: 'bfs_recursive',
    label: 'BFS',
    sublabel: 'Recursive',
    category: 'Graph',
    description: 'BFS implemented recursively by processing each level as a group.',
    complexity: { time: 'O(V+E)', space: 'O(V)' },
    inputType: 'graph',
    defaultInput: {
      nodes: 'A, B, C, D, E',
      edges: 'A-B, A-C, B-D, C-E',
      start: 'A',
    },
    inputLabel: 'Graph & start node',
    inputHint: 'Nodes: comma-separated. Edges: node-node pairs. Start: starting node.',
    run: runBFSRecursive,
  },
  {
    id: 'dfs_iterative',
    label: 'DFS',
    sublabel: 'Iterative',
    category: 'Graph',
    description: 'Explores as deep as possible using a stack before backtracking.',
    complexity: { time: 'O(V+E)', space: 'O(V)' },
    inputType: 'graph',
    defaultInput: {
      nodes: 'A, B, C, D, E',
      edges: 'A-B, A-C, B-D, C-E',
      start: 'A',
    },
    inputLabel: 'Graph & start node',
    inputHint: 'Nodes: comma-separated. Edges: node-node pairs. Start: starting node.',
    run: runDFSIterative,
  },
  {
    id: 'dfs_recursive',
    label: 'DFS',
    sublabel: 'Recursive',
    category: 'Graph',
    description: 'Explores depth-first using the call stack itself for backtracking.',
    complexity: { time: 'O(V+E)', space: 'O(V)' },
    inputType: 'graph',
    defaultInput: {
      nodes: 'A, B, C, D, E',
      edges: 'A-B, A-C, B-D, C-E',
      start: 'A',
    },
    inputLabel: 'Graph & start node',
    inputHint: 'Nodes: comma-separated. Edges: node-node pairs. Start: starting node.',
    run: runDFSRecursive,
  },
];